accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'


urlpatterns = [

    path('login/', login_view, name='login'),

    path('register/', register_view, name='register'),

    path('logout/', logout_view, name='logout'),

]

corporate/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from about.views import about_view
from contact.views import contact_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home_view, name='home'),

    path('about/', about_view, name='about'),

    path('contact/', contact_view, name='contact'),

    path('product/', include('product.urls')),

    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('index/', product_index, name='index'),
    path('<slug:slug>/', product_detail, name='detail'),
]

about/models.py
from django.db import models


class About(models.Model):
     title = models.CharField(max_length=150, verbose_name='Başlık')
     content = models.TextField(verbose_name='İçerik')
     image = models.ImageField(null=True, blank=True)

     def __str__(self):
         return self.title

accounts/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

class Feedback(models.Model):
    name = models.CharField(max_length=150, verbose_name='İsim')
    email = models.CharField(max_length=150, verbose_name='email')
    topic = models.CharField(max_length=150, verbose_name='Konu')
    content = models.TextField(verbose_name='İçerik')

home/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify



class Product(models.Model):
    product_code = models.CharField(max_length=30, verbose_name='Ürün Kodu')
    name = models.CharField(max_length=120, verbose_name='Ürün Adı')
    stock = models.IntegerField(verbose_name='Ürün Adedi')
    price = models.FloatField(verbose_name='Ürün Fiyatı')
    image = models.ImageField(null=True, blank=True)
    slug = models.SlugField(unique=True, editable=False, max_length=130)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:detail', kwargs={'slug':self.slug})

    def get_unique_slug(self):
        slug = slugify(self.name.replace('ı','i'))
        unique_slug = slug
        counter = 1
        while Product.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug,counter)
            counter += 1
        return unique_slug

    def save(self, *args, **kwargs):
        self.slug = self.get_unique_slug()
        return super(Product, self).save(*args,**kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('Kullanıcı adını veya parolayı yanlış girdiniz!')
        return super(LoginForm, self).clean()

class RegisterForm  (forms.ModelForm):
    email = forms.EmailField(max_length=245)
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password1 = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label='Parola Doğrulama', widget=forms.PasswordInput)
    phone = forms.CharField(max_length=15, label='Telefon')
    address = forms.CharField(max_length=140, label='Adres')

    class Meta:
        model = User
        fields =[
            'email',
            'username',
            'password1',
            'password2',
            'phone',
            'address',
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('passwor2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Parolalar eşleşmiyor!')
        return password2

contact/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = [
            'name',
            'email',
            'topic',
            'content',
        ]

about/views.py
from django.shortcuts import render,get_object_or_404
from .models import About


def about_view(request):
    about =get_object_or_404(About)

    context = {
        'about': about,
    }


    return render(request, 'about.html', context)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import LoginForm,RegisterForm
from django.contrib.auth import authenticate,login,logout

def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    return render(request, 'accounts/form.html',{'form': form, 'title':'Giriş Yap'})


def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password2')
        user.set_password(password)
        user.save()
        new_user = authenticate(username = user.username, password=password)
        login(request,new_user)
        return redirect('home')
    return render(request, 'accounts/form.html', {'form':form, 'title':'Üye Ol'})

def logout_view(request):
    logout(request)
    return redirect('home')

contact/views.py
from django.shortcuts import render,redirect
from .forms import FeedbackForm
from django.contrib import messages

def contact_view(request):

    form = FeedbackForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'İsteğiniz başarılı bir şekilde alınmıştır.')
        return redirect('contact')


    context = {
        'form': form,
    }
    return render(request, 'contact.html', context)

home/views.py
from django.shortcuts import render,get_object_or_404
from product.models import Product


def home_view(request):
    product = Product.objects.all()
    context = {
        'products': product,
    }
    return render(request, 'home.html', context)

product/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q


def product_index(request):
    products_list = Product.objects.all()

    #Search
    query = request.GET.get('q')
    if query:
        products_list = products_list.filter(Q(name__icontains=query)).distinct()

    #Paginator
    paginator = Paginator(products_list, 12)  # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    return render(request, 'product/index.html', {'products':products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    context = {
        'product': product,
    }
    return render(request, 'product/detail.html', context)

templates/about.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-8 text-center offset-2">
                {% if about.image %}
                    <img class="card-img-top" src="{{ about.image.url }}" alt="Card image cap" >
                {% endif %}
                <div class="col"><hr></div>
                <h5 class="text-center">{{ about.title }}</h5>
                <div class="col"><hr></div>
                <p class="text-justify">{{ about.content }}</p>
            </div>
        </div>
    </div>


{% endblock %}

templates/accounts/form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-3">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1>{{ title }}</h1>
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="{{ title }}">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8" name="viewport" content="width-device-witdh; initial-scale=1">
    <title>{% block title %}Kurum Adı{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include 'header.html' %}

    {% include 'messages.html' %}

    {% block body %}

    {% endblock %}

    <br>

    {% include 'footer.html' %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}


    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-3">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Gönder">
                </form>
            </div>
        </div>
    </div>

    <br>



{% endblock %}

templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small lighten-5 " style="background-color: rgba(84,84,84,0.53)">

    <br>


  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Company name</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Products</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="#!">MDBootstrap</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">MDWordPress</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">BrandFlow</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Bootstrap Angular</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="#!">Your Account</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Shipping Rates</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> info@example.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-black-50 py-3" style="background-color: rgba(35,35,35,0.53)">© 2018 Copyright
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/header.html
        <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light navbar-collapse">
          <a class="navbar-brand" href="{% url 'home' %}">Kurum Adı</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Anasayfa <span class="sr-only">(current)</span></a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'product:index' %}">Ürünlerimiz</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">Hakkımızda</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">İletişim</a></li>

                {% if not request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Giriş Yap</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Üye Ol</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış Yap</a></li>
                {% endif %}

            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" name="q" placeholder="Ürünü Ara" aria-label="Search" value="{{ request.GET.q }}">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ara</button>
            </form>
          </div>
        </nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}Anasayfa-{{ block.super }}{% endblock %}

{% block body %}

    {% include 'slider.html' %}

{% endblock %}

templates/messages.html
{% if messages %}

    <ul class="messages">

        {% for message in messages %}


            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

        {% endfor %}

    </ul>
{% endif %}

templates/product/detail.html
{% extends 'base.html' %}

{% block body %}

     <div class="container">
        <div class="row">
              <div class="col-md-8 offset-2">
                <div class="card">
                    {% if product.image %}
                        <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
                    {% endif %}

                    <hr>

                    <div class="card-body">
                        <a class="card-title"><h5>{{ product.name }}</h5></a>
                            <p><small>{{ product.product_code }}</small></p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Ürün Adedi : {{ product.stock }}</li>
                        <li class="list-group-item">Ürün Fiyatı : {{ product.price }} Türk Lirası</li>
                    </ul>
                </div>
              </div>
          </div>
        </div>
    </div>

{% endblock %}

templates/product/index.html
{% extends 'base.html' %}

{% block body %}

        <div class="container">
            <div class="row">
                {% for product in products %}
                    <div class="col-sm-6 col-md-4">
                        <div class="card" style="height: 650px">
                            {% if product.image %}
                                <a href="{{ product.get_absolute_url }}"><img class="card-img-top " src="{{ product.image.url }}" alt="Card image cap"  style="height: 400px; object-fit: contain;padding: 20px"></a>
                            {% endif %}
                            <hr>
                              <div class="card-body">
                                  <a class="card-title"><a href="{{ product.get_absolute_url }}"> {{ product.name|truncatechars:40 }}</a></h5>
                                      <p><small>{{ product.product_code }}</small></p>
                              </div>
                              <ul class="list-group list-group-flush">
                                <li class="list-group-item">Ürün Adedi : {{ product.stock }}</li>
                                <li class="list-group-item">Ürün Fiyatı : {{ product.price }} Türk Lirası</li>
                              </ul>
                        </div>
                    <br>
                    </div>
                {% endfor %}
            </div>
        </div>

        {#Paginator#}

        <div class="row">
          <div class="col-sm-6 col-md-4 offset-4">
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                <li class="page-item">
                    {% if products.has_previous %}
                      <a class="page-link" href="?page={{ products.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    {% endif %}
                </li>
                <li class="page-item"><a class="page-link" href="#"><span class="current">{{ products.number }} - {{ products.paginator.num_pages }}</span></a></li>
                <li class="page-item">
                    {% if products.has_next %}
                      <a class="page-link" href="?page={{ products.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    {% endif %}
                </li>
              </ul>
            </nav>
          </div>
        </div>


        </div>





{% endblock %}

templates/slider.html
{% load static %}




<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">
      {% for p in products %}

            <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                <img src="{{ p.image.url }}" alt="Image"  class="d-block w-100" style="height: 650px; width: 1920px; object-fit: contain">
                <div class="text-center">
                    <a href="{{ p.get_absolute_url }}"><h5>{{ p.name }}</h5></a>
                </div>
            </div>
      {% endfor %}


  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>